export const LANGUAGES = [
  { id: 'english', label: 'English', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/english_10k.json' },
  { id: 'spanish', label: 'Spanish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/spanish.json' },
  { id: 'french', label: 'French', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/french.json' },
  { id: 'german', label: 'German', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/german.json' },
  { id: 'portuguese', label: 'Portuguese', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/portuguese.json' },
  { id: 'italian', label: 'Italian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/italian.json' },
  { id: 'dutch', label: 'Dutch', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/dutch.json' },
  { id: 'swedish', label: 'Swedish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/swedish.json' },
  { id: 'danish', label: 'Danish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/danish.json' },
  { id: 'norwegian_bokmal', label: 'Norwegian Bokmål', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/norwegian_bokmal.json' },
  { id: 'norwegian_nynorsk', label: 'Norwegian Nynorsk', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/norwegian_nynorsk.json' },
  { id: 'finnish', label: 'Finnish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/finnish.json' },
  { id: 'icelandic', label: 'Icelandic', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/icelandic.json' },
  { id: 'irish', label: 'Irish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/irish.json' },
  { id: 'welsh', label: 'Welsh', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/welsh.json' },
  { id: 'polish', label: 'Polish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/polish.json' },
  { id: 'czech', label: 'Czech', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/czech.json' },
  { id: 'slovak', label: 'Slovak', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/slovak.json' },
  { id: 'slovenian', label: 'Slovenian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/slovenian.json' },
  { id: 'croatian', label: 'Croatian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/croatian.json' },
  { id: 'serbian', label: 'Serbian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/serbian.json' },
  { id: 'bosnian', label: 'Bosnian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/bosnian.json' },
  { id: 'romanian', label: 'Romanian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/romanian.json' },
  { id: 'bulgarian', label: 'Bulgarian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/bulgarian.json' },
  { id: 'macedonian', label: 'Macedonian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/macedonian.json' },
  { id: 'albanian', label: 'Albanian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/albanian.json' },
  { id: 'hungarian', label: 'Hungarian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hungarian.json' },
  { id: 'lithuanian', label: 'Lithuanian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/lithuanian.json' },
  { id: 'latvian', label: 'Latvian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/latvian.json' },
  { id: 'estonian', label: 'Estonian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/estonian.json' },
  { id: 'greek', label: 'Greek', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/greek.json' },
  { id: 'catalan', label: 'Catalan', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/catalan.json' },
  { id: 'galician', label: 'Galician', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/galician.json' },
  { id: 'basque', label: 'Basque (Euskera)', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/euskera.json' },
  { id: 'friulian', label: 'Friulian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/friulian.json' },
  { id: 'occitan', label: 'Occitan', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/occitan.json' },
  { id: 'frisian', label: 'Frisian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/frisian.json' },
  { id: 'maltese', label: 'Maltese', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/maltese.json' },
  { id: 'latin', label: 'Latin', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/latin.json' },
  { id: 'esperanto', label: 'Esperanto', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/esperanto.json' },
  { id: 'hindi', label: 'Hindi', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hindi.json' },
  { id: 'hinglish', label: 'Hinglish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hinglish.json' },
  { id: 'sanskrit', label: 'Sanskrit', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/sanskrit.json' },
  { id: 'sanskrit_roman', label: 'Sanskrit Roman', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/sanskrit_roman.json' },
  { id: 'bengali', label: 'Bengali / Bangla', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/bangla.json' },
  { id: 'gujarati', label: 'Gujarati', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/gujarati.json' },
  { id: 'marathi', label: 'Marathi', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/marathi.json' },
  { id: 'punjabi', label: 'Punjabi', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hindi.json' }, // Fallback to hindi since punjabi is missing
  { id: 'tamil', label: 'Tamil', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/tamil.json' },
  { id: 'tanglish', label: 'Tanglish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/tanglish.json' },
  { id: 'tamil_old', label: 'Tamil Old', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/tamil_old.json' },
  { id: 'telugu', label: 'Telugu', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/telugu.json' },
  { id: 'kannada', label: 'Kannada', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kannada.json' },
  { id: 'malayalam', label: 'Malayalam', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/malayalam.json' },
  { id: 'nepali', label: 'Nepali', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/nepali.json' },
  { id: 'nepali_romanized', label: 'Nepali Romanized', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/nepali_romanized.json' },
  { id: 'sinhala', label: 'Sinhala', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/sinhala.json' },
  { id: 'urdu', label: 'Urdu', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/urdu.json' },
  { id: 'urdu_roman', label: 'Urdu Roman', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/urdu_roman.json' },
  { id: 'sindhi', label: 'Sindhi', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/sindhi.json' },
  { id: 'santali', label: 'Santali', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/santali.json' },
  { id: 'chinese_simplified', label: 'Chinese Simplified', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/chinese_simplified.json' },
  { id: 'chinese_traditional', label: 'Chinese Traditional', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/chinese_traditional.json' },
  { id: 'pinyin', label: 'Pinyin', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/pinyin.json' },
  { id: 'jyutping', label: 'Jyutping', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/jyutping.json' },
  { id: 'japanese_hiragana', label: 'Japanese Hiragana', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/japanese_hiragana.json' },
  { id: 'japanese_katakana', label: 'Japanese Katakana', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/japanese_katakana.json' },
  { id: 'japanese_romaji', label: 'Japanese Romaji', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/japanese_romaji.json' },
  { id: 'korean', label: 'Korean', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/korean.json' },
  { id: 'vietnamese', label: 'Vietnamese', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/vietnamese.json' },
  { id: 'thai', label: 'Thai', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/thai.json' },
  { id: 'khmer', label: 'Khmer', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/khmer.json' },
  { id: 'indonesian', label: 'Indonesian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/indonesian.json' },
  { id: 'malay', label: 'Malay', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/malay.json' },
  { id: 'filipino', label: 'Filipino', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/filipino.json' },
  { id: 'mongolian', label: 'Mongolian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/mongolian.json' },
  { id: 'lao', label: 'Lao', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/lao.json' },
  { id: 'myanmar', label: 'Myanmar/Burmese', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/myanmar_burmese.json' },
  { id: 'arabic', label: 'Arabic', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/arabic.json' },
  { id: 'arabic_egyptian', label: 'Arabic Egyptian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/arabic_egypt.json' },
  { id: 'arabic_moroccan', label: 'Arabic Moroccan', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/arabic_morocco.json' },
  { id: 'persian', label: 'Persian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/persian.json' },
  { id: 'persian_romanized', label: 'Persian Romanized', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/persian_romanized.json' },
  { id: 'hebrew', label: 'Hebrew', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hebrew.json' },
  { id: 'turkish', label: 'Turkish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/turkish.json' },
  { id: 'azerbaijani', label: 'Azerbaijani', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/azerbaijani.json' },
  { id: 'kurdish_central', label: 'Kurdish Central', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kurdish_central.json' },
  { id: 'kazakh', label: 'Kazakh', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kazakh.json' },
  { id: 'kyrgyz', label: 'Kyrgyz', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kyrgyz.json' },
  { id: 'uzbek', label: 'Uzbek', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/uzbek.json' },
  { id: 'tatar', label: 'Tatar', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/tatar.json' },
  { id: 'tatar_crimean', label: 'Tatar Crimean', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/tatar_crimean.json' },
  { id: 'bashkir', label: 'Bashkir', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/bashkir.json' },
  { id: 'pashto', label: 'Pashto', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/pashto.json' },
  { id: 'armenian', label: 'Armenian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/armenian.json' },
  { id: 'georgian', label: 'Georgian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/georgian.json' },
  { id: 'afrikaans', label: 'Afrikaans', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/afrikaans.json' },
  { id: 'amharic', label: 'Amharic', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/amharic.json' },
  { id: 'bemba', label: 'Bemba', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/bemba.json' },
  { id: 'hausa', label: 'Hausa', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hausa.json' },
  { id: 'kinyarwanda', label: 'Kinyarwanda', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kinyarwanda.json' },
  { id: 'malagasy', label: 'Malagasy', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/malagasy.json' },
  { id: 'oromo', label: 'Oromo', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/oromo.json' },
  { id: 'shona', label: 'Shona', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/shona.json' },
  { id: 'swahili', label: 'Swahili', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/swahili_1k.json' },
  { id: 'xhosa', label: 'Xhosa', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/xhosa.json' },
  { id: 'yoruba', label: 'Yoruba', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/yoruba_1k.json' },
  { id: 'zulu', label: 'Zulu', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/zulu.json' },
  { id: 'kabyle', label: 'Kabyle', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kabyle.json' },
  { id: 'hawaiian', label: 'Hawaiian', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/hawaiian.json' },
  { id: 'maori', label: 'Maori', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/maori_1k.json' },
  { id: 'toki_pona', label: 'Toki Pona', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/toki_pona.json' },
  { id: 'lojban', label: 'Lojban', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/lojban_gismu.json' },
  { id: 'klingon', label: 'Klingon', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/klingon.json' },
  { id: 'quenya', label: 'Quenya', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/quenya.json' },
  { id: 'kokanu', label: 'Kokanu', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/kokanu.json' },
  { id: 'likanu', label: 'Likanu', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/likanu.json' },
  { id: 'viossa', label: 'Viossa', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/viossa.json' },
  { id: 'pig_latin', label: 'Pig Latin', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/pig_latin.json' },
  { id: 'yiddish', label: 'Yiddish', url: 'https://raw.githubusercontent.com/monkeytypegame/monkeytype/master/frontend/static/languages/yiddish.json' },
];

export function getLanguageUrl(id: string): string {
  const lang = LANGUAGES.find((l) => l.id === id);
  return lang ? lang.url : LANGUAGES[0].url;
}

export function getCurrentLanguage(): string {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('velocitype_language') || 'english';
  }
  return 'english';
}

export function setCurrentLanguage(id: string) {
  if (typeof window !== 'undefined') {
    localStorage.setItem('velocitype_language', id);
    window.dispatchEvent(new Event('languagechange'));
  }
}
